spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/assignmentdb
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: org.example.springassignment1.domain

  messages:
    basename: messages
    encoding: UTF-8
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true

logging:
  level:
    org.mybatis: DEBUG
